name: homevice
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  nb_utils: ^7.0.3
  dio: ^5.5.0+1
  get_storage: ^2.1.1
  logger: ^2.4.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
